{% set name = "django-upgrade" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-upgrade-{{ version }}.tar.gz
  sha256: 3755318596dfee20f52ba46e0ca502766c6bb45fa78e358b03d5216aea7b71c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - tokenize-rt >=4.1.0

test:
  imports:
    - django_upgrade
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-upgrade
  summary: Automatically upgrade your Django project code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gb119
